export enum RouteName {
  // START - DEMO
  SIGN_IN_DEMO = 'SIGN_IN_DEMO',
  SIGN_UP_DEMO = 'SIGN_UP_DEMO',
  FORGOT_PASSWORD_DEMO = 'FORGOT_PASSWORD_DEMO',
  MAIN_DEMO_NAV = 'MAIN_DEMO_NAV',
  AUTH_DEMO_NAV = 'AUTH_DEMO_NAV',
  TABBAR_DEMO = 'TABBAR_DEMO',
  HOME_DEMO = 'HOME_DEMO',
  ACCOUNT_DEMO = 'ACCOUNT_DEMO',
  TODO_NAV_DEMO = 'TODO_NAV_DEMO',
  TODO_LIST_DEMO = 'TODO_LIST_DEMO',
  TODO_LIST_TYPICODE_DEMO = 'TODO_LIST_TYPICODE_DEMO',
  TODO_DETAIL_DEMO = 'TODO_DETAIL_DEMO',
  REANIMATION_DEMO = 'REANIMATION_DEMO',
  // END - DEMO
  LAUNCH = 'LAUNCH',
  WEB = 'WEB',
}
