export enum RouteName {
  LAUNCH = "LAUNCH",
  SIGN_IN_DEMO = "SIGN_IN_DEMO",
  SIGN_UP_DEMO = "SIGN_UP_DEMO",
  FORGOT_PASSWORD_DEMO = "FORGOT_PASSWORD_DEMO",
  MAIN_DEMO = "MAIN_DEMO",
  AUTH_DEMO = "AUTH_DEMO",
  TABBAR_DEMO = "TABBAR_DEMO",
  HOME_DEMO = "HOME_DEMO",
  ACCOUNT_DEMO = "ACCOUNT_DEMO",
  WEB = "WEB",
}
