export enum RouteName {
  LAUNCH = "LAUNCH",
  WELCOME = "WELCOME",
  SIGN_IN = "SIGN_IN",
  SIGN_UP = "SIGN_UP",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  MAIN = "MAIN",
  AUTH = "AUTH",
  HOME = "HOME",
}
